spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/customer
    username: posgres
    password: 12345
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  data:
    mongodb:
      host: {DB_HOST}
      port: 27017
      database: customer
      username: root
      password: 12345
      authentication-database: admin
      auto-index-creation: true
